#Tugas 1

In [5]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
plt.ion()

In [10]:
dataseturl="https://raw.githubusercontent.com/Tegar11-F/Data-Set/main/smoke_detection_iot.csv"
data=pd.read_csv(dataseturl)

In [12]:
data.head(4)

,Unnamed: 0,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,CNT,Fire Alarm
0,0,1654733331,20.000,57.36,0,400,12306,18520,939.735,0.0,0.0,0.0,0.0,0.0,0,0
1,1,1654733332,20.015,56.67,0,400,12345,18651,939.744,0.0,0.0,0.0,0.0,0.0,1,0
2,2,1654733333,20.029,55.96,0,400,12374,18764,939.738,0.0,0.0,0.0,0.0,0.0,2,0
3,3,1654733334,20.044,55.28,0,400,12390,18849,939.736,0.0,0.0,0.0,0.0,0.0,3,0

## Tugas 1 : Dissimiliarity

In [ ]:
def diss (n,m):
  a = 2
  b = 0
  for col in ['Raw Ethanol','Pressure[hPa]']:
    if data[col][n] == data[col][m]:
      b+=1
  return (a-b)/a

print(diss(1,1))
print(diss(1,2))
print(diss(4,4))

0.0
1.0
0.0

## Tugas 2

There is a lot more that you can do with outputs (such as including interactive outputs)
with your book. For more information about this, see [the Jupyter Book documentation](https://jupyterbook.org)

In [6]:
datairisurl="https://raw.githubusercontent.com/Tegar11-F/Data-Set/fa20d41a8676343efb6cb833304d9fb54b807d67/IRIS.csv"
datairis=pd.read_csv(datairisurl)

In [18]:
datairis.head(150)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
from sklearn.preprocessing import KBinsDiscretizer

In [19]:
sepalLength = datairis.sepal_length
sepalWidth = datairis.sepal_width
petalLength = datairis.petal_length
petalWidth = datairis.petal_width
spesies = datairis.species

In [20]:
aa = sepalLength.values.reshape(-1,1)
ab = sepalWidth.values.reshape(-1,1)
ac = petalLength.values.reshape(-1,1)
ad = petalWidth.values.reshape(-1,1)
sp = spesies.values.reshape(-1,1)

In [21]:
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [22]:
est.fit(aa)
est.fit(ab)
est.fit(ac)
est.fit(ad)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [23]:
KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [24]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [25]:
KBinsDiscretizer(n_bins=Ellipsis)

KBinsDiscretizer(n_bins=Ellipsis)

In [26]:
xa = est.transform(aa)
xb = est.transform(ab)
xc = est.transform(ac)
xd = est.transform(ad)

In [27]:
dataa1 = {'sepal_length':xa}
dataa2 = {'sepal_length':xb}
dataa3 = {'sepal_length':xc}
dataa4 = {'sepal_length':xd}

In [29]:
fa = pd.DataFrame(xa,columns=['sepal_length'])
fb = pd.DataFrame(xb,columns=['sepal_width'])
fc = pd.DataFrame(xc,columns=['tepal_length'])
fd = pd.DataFrame(xd,columns=['tepal_width'])
spe = pd.DataFrame(sp,columns=['Species'])

In [30]:
datalist = [fa, fb, fc, fd, spe]
pd.concat(datalist, axis=1)

     sepal_length  sepal_width  tepal_length  tepal_width         Species
0             3.0          3.0           2.0          0.0     Iris-setosa
1             3.0          3.0           2.0          0.0     Iris-setosa
2             3.0          3.0           2.0          0.0     Iris-setosa
3             3.0          3.0           2.0          0.0     Iris-setosa
4             3.0          3.0           2.0          0.0     Iris-setosa
..            ...          ...           ...          ...             ...
145           3.0          3.0           3.0          3.0  Iris-virginica
146           3.0          3.0           3.0          3.0  Iris-virginica
147           3.0          3.0           3.0          3.0  Iris-virginica
148           3.0          3.0           3.0          3.0  Iris-virginica
149           3.0          3.0           3.0          2.0  Iris-virginica

[150 rows x 5 columns]